Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Scaffolding.CustomFilter.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	Public Class IssueContextResources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("IssueContextResources", GetType(IssueContextResources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Public Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

					Public Shared ReadOnly Property Issue() As String
						Get
							Return ResourceManager.GetString("Issue", resourceCulture)
						End Get
					End Property
				Public Shared ReadOnly Property Issue_Plural() As String
					Get
						Return ResourceManager.GetString("Issue_Plural", resourceCulture)
					End Get
				End Property
				Public Shared ReadOnly Property Issue_ID() As String
					Get
						Return ResourceManager.GetString("Issue_ID", resourceCulture)
					End Get
				End Property
				Public Shared ReadOnly Property Issue_IssueType() As String
					Get
						Return ResourceManager.GetString("Issue_IssueType", resourceCulture)
					End Get
				End Property
				Public Shared ReadOnly Property Issue_Subject() As String
					Get
						Return ResourceManager.GetString("Issue_Subject", resourceCulture)
					End Get
				End Property
				Public Shared ReadOnly Property Issue_IsUrgent() As String
					Get
						Return ResourceManager.GetString("Issue_IsUrgent", resourceCulture)
					End Get
				End Property
				Public Shared ReadOnly Property Issue_CreatedOn() As String
					Get
						Return ResourceManager.GetString("Issue_CreatedOn", resourceCulture)
					End Get
				End Property

	End Class
End Namespace

